name: Unit Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Discover cores
        if: ${{ matrix.os != 'macos-latest' }}
        run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'

      - name: Print Compiler version
        # NOTE: on mac, this is actually symlink'd to clang, not gcc, but that's ok - we want to build on both
        working-directory: .
        run: gcc -v

      - name: Build Tests
        working-directory: ./SENT-box/unit_tests/
        run: make -j4 COVERAGE=yes

      - name: Run Tests
        working-directory: ./SENT-box/unit_tests/
        run: ASAN_OPTIONS=detect_stack_use_after_return=1 build/sent_test
